FROM tomcat:9.0
   COPY target/HelloWorldApp.war /usr/local/tomcat/webapps/
   EXPOSE 8080
   CMD ["catalina.sh", "run"]



# Use official Tomcat 9 base image (latest stable)
FROM tomcat:9.0-jdk17-temurin

# Remove default ROOT application (optional but clean)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR generated by Maven into Tomcat's webapps directory
COPY target/HelloWorldApp.war /usr/local/tomcat/webapps/HelloWorldApp.war

# Expose Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
